### ISSUE TITLE
Looking for docs

### ISSUE THREAD

**Issue by Velliz** [robisemicolon/HamPHP#1]
I feel this framework is great but i can't find the docs. 
Even the readme.md file is not provided.

Please provide an example or guide. So i can try and evaluate your works.
Thanks.

**Comment by ammarfaizi2** [comment]
Thank you mr @Velliz 
I also think this is a good idea, but its implementation is very difficult. Because i don't have experience about make documentation. But i will try it.

cc repo owner @robisemicolon

**Comment by hadihammurabi** [comment]
@Velliz Now, the documentation is not provided yet. It will created next time.

**Comment by Velliz** [comment]
ok, notice me if the docs is ready 👍

**Comment by hadihammurabi** [comment]
Ok, thanks for your feed back.

**Comment by Djenova** [comment]
i think you should create documentation or Readme ASAP @robisemicolon thank you 👍

**Comment by hadihammurabi** [comment]
You'rwelcome, @Djenova. Documentation is an item in this project to do list.

**Comment by Velliz** [comment]
Is this project abandoned now??

**Comment by hadihammurabi** [comment]
> Is this project abandoned now??

Do you want to contribute or refactor somethings?
We can discuss about contributions more.
