### ISSUE TITLE
Error when i try using index.php in url

### ISSUE THREAD

**Issue by ppabcd** [robisemicolon/HamPHP#3]
In this project i don't see .htaccess files. When i want to change controller using http://ham.dev/index.php/controller but server always read index.php as  controller.
![alt text](https://image.prntscr.com/image/umt-Fgj9QEeBIQATljscQA.png)
![alt text](https://image.prntscr.com/image/RaRQ1jZXQ-WlZFSqOOAnTQ.png)

**Comment by hadihammurabi** [comment]
This framework not using .htaccess file, because it is not just used for Apache Web Server. So, it will fixed by PHP code. Thanks for your feed back.

**Comment by hadihammurabi** [comment]
This issue was fixed, @ppabcd . You can try to clone this again.
